### ISSUE TITLE
Pycse dependencies

### ISSUE THREAD

**Issue by ktran9891** [zulissi/f17-06625#1]
When executing the 2nd cell of `rxns-book/generalized-effectiveness-factors.ipynb`:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-6f9d3e8c278e> in <module>()
      1 import numpy as np
----> 2 from pycse import BVP_nl
      3 import matplotlib.pyplot as plt
      4 
      5 n = [1.0, 2.0, 3.0]     # reaction order

ImportError: cannot import name 'BVP_nl'
```

**Comment by ktran9891** [comment]
in `rxns-book/parameter-estimation.ipynb`, there is a section that relies on a `data` object that I suspect is imported via Pycse. There are also some links and problems that rely on Pycse.

**Comment by ktran9891** [comment]
In `rxns-book/rate-laws.ipynb`, there are some links to `pycse.odelay`.

**Comment by ktran9891** [comment]
In `rxns-book/wrapping-up-introduction.ipynb`, Pycse dependencies are present throughout.

**Comment by zulissi** [comment]
I think pycse should be good to go.  The BVP_nl problem was fixed with a different import statement.  Otherwise, I think they're working.
